name: triagain
description: "TriAgain - Start Small. Try Again."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  go_router: ^14.8.1
  dio: ^5.7.0
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  google_fonts: ^6.2.1
  riverpod_annotation: ^2.6.1
  uuid: ^4.5.1
  share_plus: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3
  riverpod_generator: ^2.6.3
  build_runner: ^2.4.14
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "images/logo.png"
  remove_alpha_ios: true
  background_color_android: "#000000"
  background_color_ios: "#000000"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - images/
